# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains_projects', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('summary_level', models.CharField(choices=[('thread', 'Thread'), ('project', 'Project'), ('monthly', 'Monthly'), ('global', 'Global')], max_length=32)),
                ('summary_text', models.TextField()),
                ('source_message_ids', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('version', models.PositiveIntegerField(default=1)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains_projects.domain')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains_projects.project')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threads.thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
