# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_profiles', '0001_initial'),
        ('contacts', '0001_initial'),
        ('domains_projects', '0001_initial'),
        ('secrets', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_message_id', models.BigIntegerField()),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_type', models.CharField(choices=[('owner', 'Owner'), ('agent', 'Agent'), ('subagent', 'Subagent'), ('system', 'System'), ('external', 'External')], max_length=32)),
                ('raw_text', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('routing_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('value_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('noise_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rag_eligibility', models.CharField(choices=[('excluded', 'Excluded'), ('archive_only', 'Archive Only'), ('summary_only', 'Summary Only'), ('retrieval_allowed', 'Retrieval Allowed'), ('priority_retrieval', 'Priority Retrieval')], default='retrieval_allowed', max_length=32)),
                ('message_value_tier', models.CharField(choices=[('T0_NOISE', 'Noise'), ('T1_EPHEMERAL', 'Ephemeral'), ('T2_PROJECT', 'Project'), ('T3_DURABLE', 'Durable'), ('T4_CRITICAL', 'Critical')], default='T1_EPHEMERAL', max_length=32)),
                ('message_role', models.CharField(choices=[('owner_idea', 'Owner Idea'), ('owner_decision', 'Owner Decision'), ('owner_instruction', 'Owner Instruction'), ('agent_reasoning_trace', 'Agent Reasoning Trace'), ('agent_output', 'Agent Output'), ('debug_trace', 'Debug Trace'), ('test_result', 'Test Result'), ('code_instruction', 'Code Instruction'), ('ops_instruction', 'Ops Instruction'), ('git_event', 'Git Event'), ('prompt_fragment', 'Prompt Fragment'), ('task_assignment', 'Task Assignment'), ('contact_reference', 'Contact Reference'), ('system_event', 'System Event')], default='owner_idea', max_length=64)),
                ('sensitivity_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('secret', 'Secret')], default='internal', max_length=32)),
                ('retrieval_mode_default', models.CharField(choices=[('business_mode', 'Business'), ('debug_mode', 'Debug'), ('ops_mode', 'Ops'), ('historical_mode', 'Historical')], default='business_mode', max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Embedding vector placeholder for P0; move to pgvector in P1.', null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains_projects.domain')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains_projects.project')),
                ('sender_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threads.thread')),
            ],
        ),
        migrations.CreateModel(
            name='MessageContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('relation_type', models.CharField(blank=True, max_length=64)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='contacts.contact')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='chat_events.message')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('target_chat_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_text', models.TextField(blank=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_deliveries', to='chat_events.message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('source_kind', models.CharField(choices=[('live_bot', 'Live Bot'), ('archive_import', 'Archive Import')], max_length=32)),
                ('bot_username', models.CharField(blank=True, max_length=255)),
                ('telegram_bot_id', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('default_retrieval_mode', models.CharField(choices=[('business_mode', 'Business'), ('debug_mode', 'Debug'), ('ops_mode', 'Ops'), ('historical_mode', 'Historical')], default='business_mode', max_length=64)),
                ('source_prompt_prefix', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_inbound_enabled', models.BooleanField(default=True)),
                ('is_outbound_enabled', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bot_token_secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_sources', to='secrets.secretrecord')),
                ('default_agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_sources', to='agent_profiles.agentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
