# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_events', '0001_initial'),
        ('context_packs', '0001_initial'),
        ('domains_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsource',
            name='default_context_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_sources', to='context_packs.contextpack'),
        ),
        migrations.AddField(
            model_name='telegramsource',
            name='default_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains_projects.domain'),
        ),
        migrations.AddField(
            model_name='telegramsource',
            name='default_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains_projects.project'),
        ),
        migrations.AddField(
            model_name='outbounddeliverylog',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='chat_events.telegramsource'),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_events.telegramsource'),
        ),
        migrations.AlterUniqueTogether(
            name='messagecontactlink',
            unique_together={('message', 'contact')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source', 'timestamp'], name='chat_events_source__029e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['domain', 'project', 'thread'], name='chat_events_domain__4a599d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_role', 'retrieval_mode_default'], name='chat_events_message_1bdd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['project', 'timestamp'], name='chat_events_project_43e162_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source', 'project', 'timestamp'], name='chat_events_source__6a9c71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('source', 'telegram_chat_id', 'telegram_message_id')},
        ),
    ]
