# Generated by Django 5.2.13 on 2026-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_events', '0005_outbounddeliveryattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbounddeliveryattempt',
            name='last_error_code',
            field=models.CharField(blank=True, help_text='Telegram error code (e.g. 429, 403)', max_length=64),
        ),
        migrations.AlterField(
            model_name='outbounddeliveryattempt',
            name='retry_after',
            field=models.IntegerField(default=0, help_text='Telegram rate-limit backoff seconds'),
        ),
        migrations.AlterField(
            model_name='outbounddeliveryattempt',
            name='telegram_response_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Raw Telegram API response'),
        ),
    ]
