# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('canonical_name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('dormant', 'Dormant'), ('archived', 'Archived'), ('merged', 'Merged')], default='active', max_length=32)),
                ('importance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='domains_projects.domain')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='domains_projects.project')),
            ],
            options={
                'unique_together': {('domain', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('relation_type', models.CharField(choices=[('related_to', 'Related To'), ('depends_on', 'Depends On'), ('subproject_of', 'Subproject Of'), ('shares_contact_with', 'Shares Contact With')], max_length=64)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='domains_projects.project')),
                ('target_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='domains_projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
