# Generated by Django 5.2.13 on 2026-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('canonical_name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('telegram_handle', models.CharField(blank=True, max_length=255)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
