# Generated by Django 5.2.13 on 2026-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_hardening_p2_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobqueue',
            options={'ordering': ['-priority', 'available_at']},
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='attempt_count',
            field=models.IntegerField(default=0, help_text='Current retry attempt number'),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='available_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='dead_letter_reason',
            field=models.TextField(blank=True, help_text='Reason why job was moved to dead-letter'),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Prevents duplicate execution of the same job', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='job_type',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Last alive signal from worker', null=True),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='max_attempts',
            field=models.IntegerField(default=3, help_text='Maximum retry attempts before dead-letter'),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='priority',
            field=models.IntegerField(db_index=True, default=100),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('retry', 'Retry'), ('dead_letter', 'Dead Letter'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, help_text='Distributed tracing identifier', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='worker_name',
            field=models.CharField(blank=True, help_text='Identifier of the worker processing this job', max_length=128),
        ),
        migrations.AddIndex(
            model_name='jobqueue',
            index=models.Index(fields=['status', 'priority', 'available_at'], name='idx_jobs_queue_poll'),
        ),
        migrations.AddIndex(
            model_name='jobqueue',
            index=models.Index(fields=['job_type', 'status'], name='idx_jobs_type_status'),
        ),
        migrations.AlterModelTable(
            name='jobqueue',
            table='jobs_jobqueue',
        ),
    ]
