# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('domain', 'Domain'), ('project', 'Project'), ('thread', 'Thread'), ('agent_profile', 'Agent Profile')], max_length=32)),
                ('scope_id', models.BigIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('secret_kind', models.CharField(max_length=64)),
                ('encrypted_value', models.BinaryField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('access_policy', models.JSONField(blank=True, default=dict)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecretAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('agent_profile_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_type', models.CharField(max_length=32)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('access_mode', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('secret_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='secrets.secretrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
