# Generated by Django 5.2.13 on 2026-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_approval_p2_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaccesslog',
            name='granted_by_id',
            field=models.BigIntegerField(blank=True, help_text='User who granted access', null=True),
        ),
        migrations.AlterField(
            model_name='secretaccesslog',
            name='revoke_reason',
            field=models.TextField(blank=True, help_text='Reason for revocation'),
        ),
        migrations.AlterField(
            model_name='secretaccesslog',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='When grant was revoked', null=True),
        ),
    ]
