# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains_projects', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('knowledge_type', models.CharField(choices=[('fact', 'Fact'), ('decision', 'Decision'), ('task', 'Task'), ('rule', 'Rule'), ('heuristic', 'Heuristic'), ('hypothesis', 'Hypothesis'), ('prompt', 'Prompt'), ('lesson', 'Lesson')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('status', models.CharField(default='candidate', max_length=32)),
                ('source_message_ids', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Embedding vector for semantic search', null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains_projects.domain')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains_projects.project')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threads.thread')),
            ],
            options={
                'indexes': [models.Index(fields=['domain', 'project'], name='knowledge_k_domain__d1478a_idx'), models.Index(fields=['knowledge_type', 'status'], name='knowledge_k_knowled_78957b_idx')],
            },
        ),
    ]
