# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('page_type', models.CharField(choices=[('global_overview', 'Global Overview'), ('domain_overview', 'Domain Overview'), ('project_overview', 'Project Overview'), ('architecture', 'Architecture'), ('analysis', 'Analysis'), ('decision_log', 'Decision Log'), ('archive_guide', 'Archive Guide'), ('operations', 'Operations'), ('secret_reference', 'Secret Reference'), ('custom', 'Custom')], max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.BigIntegerField()),
                ('link_kind', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('wiki_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='wiki.wikipage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content_text', models.TextField()),
                ('content_format', models.CharField(default='markdown', max_length=32)),
                ('author_type', models.CharField(default='human', max_length=32)),
                ('source_summary_ids', models.JSONField(blank=True, default=list)),
                ('source_knowledge_item_ids', models.JSONField(blank=True, default=list)),
                ('source_message_ids', models.JSONField(blank=True, default=list)),
                ('wiki_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.wikipage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('domain', 'Domain'), ('project', 'Project'), ('thread', 'Thread'), ('agent_profile', 'Agent Profile')], max_length=32)),
                ('scope_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('scope_type', 'scope_id')},
            },
        ),
        migrations.AddField(
            model_name='wikipage',
            name='wiki_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wiki.wikispace'),
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('wiki_space', 'slug')},
        ),
    ]
