# Generated by Django 5.2.13 on 2026-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('source_path', models.CharField(blank=True, max_length=512)),
                ('total_messages', models.IntegerField(default=0)),
                ('processed_messages', models.IntegerField(default=0)),
                ('imported_artifacts', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
