# Generated by Django 5.2.13 on 2026-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveimportjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='archiveimportjob',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='archiveimportjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('parsing', 'Parsing'), ('processing', 'Processing'), ('chunking', 'Chunking'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
        migrations.AlterModelTable(
            name='archiveimportjob',
            table='archive_import_jobs',
        ),
    ]
