# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        ('chat_events', '0001_initial'),
        ('domains_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='linked_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='chat_events.message'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='domains_projects.project'),
        ),
    ]
