# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_profiles', '0001_initial'),
        ('chat_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('domain', 'Domain'), ('project', 'Project'), ('thread', 'Thread'), ('agent_profile', 'Agent Profile')], max_length=32)),
                ('scope_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('human_readable_text', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('parent_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_packs.contextpack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('context_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='context_packs.contextpack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rule_type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_when', models.JSONField(blank=True, default=dict)),
                ('context_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='context_packs.contextpack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=128)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('value_text', models.TextField(blank=True)),
                ('value_type', models.CharField(default='json', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('context_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='context_packs.contextpack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('skill_key', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('invocation_policy', models.CharField(default='manual_or_auto', max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('context_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='context_packs.contextpack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceAgentBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='agent_profiles.agentprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_bindings', to='chat_events.telegramsource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceContextBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=True)),
                ('context_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='context_packs.contextpack')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_bindings', to='chat_events.telegramsource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
