# Generated by Django 5.2.13 on 2026-04-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('query_text', models.TextField()),
                ('routing_snapshot', models.JSONField(blank=True, default=dict)),
                ('selected_message_ids', models.JSONField(blank=True, default=list)),
                ('selected_summary_ids', models.JSONField(blank=True, default=list)),
                ('selected_knowledge_item_ids', models.JSONField(blank=True, default=list)),
                ('selected_prompt_ids', models.JSONField(blank=True, default=list)),
                ('applied_context_pack_ids', models.JSONField(blank=True, default=list)),
                ('final_prompt_text', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('model_output', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_sessions', to='chat_events.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
