# Generated by Django 5.2.13 on 2026-04-23 11:28

import apps.core.vector
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_events', '0006_alter_outbounddeliveryattempt_last_error_code_and_more'),
        ('domains_projects', '0001_initial'),
        ('retrieval', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('query_count', models.PositiveIntegerField(default=0)),
                ('average_recall_at_5', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_mrr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='retrievalsession',
            name='diagnostics_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='retrievalsession',
            name='runtime_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='retrievalsession',
            name='selected_corpus_entry_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RetrievalEvaluationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('query_text', models.TextField()),
                ('retrieval_mode', models.CharField(choices=[('business_mode', 'Business'), ('debug_mode', 'Debug'), ('ops_mode', 'Ops'), ('historical_mode', 'Historical')], default='business_mode', max_length=64)),
                ('expected_corpus_entry_ids', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_eval_cases', to='domains_projects.domain')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_eval_cases', to='domains_projects.project')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_eval_cases', to='chat_events.telegramsource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetrievalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rating', models.SmallIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('reviewer', models.CharField(blank=True, max_length=128)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='retrieval.retrievalsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('queue_type', models.CharField(choices=[('project_merge', 'Project Merge'), ('thread_review', 'Thread Review'), ('message_relabel', 'Message Relabel'), ('knowledge_promotion', 'Knowledge Promotion'), ('wiki_draft', 'Wiki Draft'), ('retrieval_outlier', 'Retrieval Outlier')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='open', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=100)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_items', to='domains_projects.domain')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_items', to='domains_projects.project')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_items', to='chat_events.telegramsource')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RagCorpusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entry_type', models.CharField(choices=[('message', 'Message'), ('summary', 'Summary'), ('knowledge', 'Knowledge'), ('wiki', 'Wiki'), ('rule', 'Rule')], max_length=32)),
                ('source_object_type', models.CharField(choices=[('message', 'Message'), ('summary', 'Summary'), ('knowledge', 'Knowledge'), ('wiki_page', 'Wiki Page'), ('context_rule', 'Context Rule')], max_length=32)),
                ('source_object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message_role', models.CharField(blank=True, max_length=64)),
                ('retrieval_mode', models.CharField(choices=[('business_mode', 'Business'), ('debug_mode', 'Debug'), ('ops_mode', 'Ops'), ('historical_mode', 'Historical')], default='business_mode', max_length=64)),
                ('sensitivity_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('secret', 'Secret')], default='internal', max_length=32)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('freshness_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('source_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('retrieval_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('storage_tier', models.CharField(default='hot', max_length=16)),
                ('redaction_status', models.CharField(default='clean', max_length=16)),
                ('duplicate_group_key', models.CharField(blank=True, max_length=128)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding', apps.core.vector.EmbeddingField(blank=True, default=list, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_entries', to='domains_projects.domain')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_entries', to='domains_projects.project')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_entries', to='chat_events.telegramsource')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_entries', to='threads.thread')),
            ],
            options={
                'indexes': [models.Index(fields=['entry_type', 'is_active'], name='retrieval_r_entry_t_9d3d44_idx'), models.Index(fields=['source_object_type', 'source_object_id'], name='retrieval_r_source__e6fe79_idx'), models.Index(fields=['domain', 'project', 'thread'], name='retrieval_r_domain__3169b4_idx'), models.Index(fields=['retrieval_mode', 'message_role'], name='retrieval_r_retriev_78f0ea_idx'), models.Index(fields=['source', 'project'], name='retrieval_r_source__e3f0e4_idx'), models.Index(fields=['trust_score', 'freshness_score'], name='retrieval_r_trust_s_0cacf5_idx'), models.Index(fields=['source_weight', 'retrieval_weight'], name='retrieval_r_source__3d6a34_idx'), models.Index(fields=['storage_tier', 'redaction_status'], name='retrieval_r_storage_d19520_idx'), models.Index(fields=['duplicate_group_key'], name='retrieval_r_duplica_fea691_idx')],
                'unique_together': {('source_object_type', 'source_object_id')},
            },
        ),
        migrations.CreateModel(
            name='RetrievalEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('retrieved_entry_ids', models.JSONField(blank=True, default=list)),
                ('recall_at_5', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='retrieval.retrievalevaluationcase')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='retrieval.retrievalevaluationrun')),
            ],
            options={
                'unique_together': {('run', 'case')},
            },
        ),
    ]
